// src/WebUI/ClientApp-Nuxt/components/NavMenu.vue
﻿<template>
  <header>
    <BNavbar className="navbar-expand-sm navbar-toggleable-sm ng-white border-bottom box-shadow mb-3" container light>
      <BNavbarBrand tag={Link} to="/">WebUI</BNavbarBrand>
      <BNavbarToggle onClick={this.toggleNavbar} className="mr-2" />
      <BCollapse className="d-sm-inline-flex flex-sm-row-reverse" isOpen={!this.state.collapsed} navbar>
        <ul className="navbar-nav flex-grow">
          <BNavItem>
            <b-link tag={Link} href="/" target="_blank" class="text-dark">Home</b-link>
          </BNavItem>
          <BNavItem>
            <b-link tag={Link} href="/counter" className="text-dark">Counter</b-link>
          </BNavItem>
          <BNavItem>
            <b-link tag={Link} href="/fetch-data" className="text-dark">Fetch data</b-link>
          </BNavItem>
          <BNavItem>
            <a class="nav-link text-dark" href="/Identity/Account/Manage">Account</a>
          </BNavItem>
        </ul>
      </BCollapse>
    </BNavbar>
  </header>
</template>
<script setup>
const toggle = ref(false);

function toggleNavbar () {
  toggle.value = !toggle.value;
}

</script>
<style>
a.navbar-brand {
  white-space: normal;
  text-align: center;
  word-break: break-all;
}

html {
  font-size: 14px;
}
@media (min-width: 768px) {
  html {
    font-size: 16px;
  }
}

.box-shadow {
  box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05);
}

</style>

// src/WebUI/ClientApp-React/src/components/NavMenu.js
import React, { Component } from 'react';
import { Collapse, Navbar, NavbarBrand, NavbarToggler, NavItem, NavLink } from 'reactstrap';
import { Link } from 'react-router-dom';
import './NavMenu.css';

export class NavMenu extends Component {
  static displayName = NavMenu.name;

  constructor (props) {
    super(props);

    this.toggleNavbar = this.toggleNavbar.bind(this);
    this.state = {
      collapsed: true
    };
  }

  toggleNavbar () {
    this.setState({
      collapsed: !this.state.collapsed
    });
  }

  render() {
    return (
      <header>
        <Navbar className="navbar-expand-sm navbar-toggleable-sm ng-white border-bottom box-shadow mb-3" container light>
          <NavbarBrand tag={Link} to="/">WebUI</NavbarBrand>
          <NavbarToggler onClick={this.toggleNavbar} className="mr-2" />
          <Collapse className="d-sm-inline-flex flex-sm-row-reverse" isOpen={!this.state.collapsed} navbar>
            <ul className="navbar-nav flex-grow">
              <NavItem>
                <NavLink tag={Link} className="text-dark" to="/">Home</NavLink>
              </NavItem>
              <NavItem>
                <NavLink tag={Link} className="text-dark" to="/counter">Counter</NavLink>
              </NavItem>
              <NavItem>
                <NavLink tag={Link} className="text-dark" to="/fetch-data">Fetch data</NavLink>
              </NavItem>
              <NavItem>
                <a className="nav-link text-dark" href="/Identity/Account/Manage">Account</a>
              </NavItem>
            </ul>
          </Collapse>
        </Navbar>
      </header>
    );
  }
}
