// src/WebUI/ClientAppNuxt/components/Nav/LoginMenu.vue
<script>
const isAuthenticated = ref(false);
const userName = ref("test user name");
</script>
<template>
  <ul class="navbar-nav" v-if="isAuthenticated">
    <li class="nav-item">
      <NuxtLink
        class="nav-link text-dark"
        [routerLink]='["/NuxtLinkuthentication/profile"]'
        title="Manage"
        >Hello {{ userName }}</NuxtLink
      >
    </li>
    <li class="nav-item">
      <NuxtLink
        class="nav-link text-dark"
        [routerLink]='["/NuxtLinkuthentication/logout"]'
        [state]="{ local: true }"
        title="Logout"
        >Logout</NuxtLink
      >
    </li>
  </ul>
  <ul class="navbar-nav" v-if="!isAuthenticated">
    <li class="nav-item">
      <NuxtLink
        class="nav-link text-dark"
        [routerLink]='["/NuxtLinkuthentication/register"]'
        >Register</NuxtLink
      >
    </li>
    <li class="nav-item">
      <NuxtLink
        class="nav-link text-dark"
        [routerLink]='["/NuxtLinkuthentication/login"]'
        >Login</NuxtLink
      >
    </li>
  </ul>
</template>

// src/WebUI/ClientApp/src/api-authorization/login-menu/login-menu.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthorizeService } from '../authorize.service';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-login-menu',
  templateUrl: './login-menu.component.html',
  styleUrls: ['./login-menu.component.scss']
})
export class LoginMenuComponent implements OnInit {
  public isAuthenticated?: Observable<boolean>;
  public userName?: Observable<string | null | undefined>;

  constructor(private authorizeService: AuthorizeService) { }

  ngOnInit() {
    this.isAuthenticated = this.authorizeService.isAuthenticated();
    this.userName = this.authorizeService.getUser().pipe(map(u => u && u.name));
  }
}

<ul class="navbar-nav" *ngIf="isAuthenticated | async">
    <li class="nav-item">
        <a  class="nav-link text-dark" [routerLink]='["/authentication/profile"]' title="Manage">Hello {{ userName | async }}</a>
    </li>
    <li class="nav-item">
        <a  class="nav-link text-dark" [routerLink]='["/authentication/logout"]' [state]='{ local: true }' title="Logout">Logout</a>
    </li>
</ul>
<ul class="navbar-nav" *ngIf="(isAuthenticated | async) !== true">
  <li class="nav-item">
        <a class="nav-link text-dark" [routerLink]='["/authentication/register"]'>Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" [routerLink]='["/authentication/login"]'>Login</a>
    </li>
</ul>
