// src/Web/ClientApp/src/app/theme-toggle/theme-toggle.component.ts
import { Component, computed } from '@angular/core';
import { ThemeService, Theme } from '../theme.service';

@Component({
  standalone: false,
  selector: 'app-theme-toggle',
  templateUrl: './theme-toggle.component.html'
})
export class ThemeToggleComponent {
  constructor(public themeService: ThemeService) {}

  icon = computed(() => {
    switch (this.themeService.theme()) {
      case 'light': return 'sun';
      case 'dark':  return 'moon';
      default:      return 'laptop';
    }
  });

  label = computed(() => {
    switch (this.themeService.theme()) {
      case 'light': return 'Light';
      case 'dark':  return 'Dark';
      default:      return 'Auto';
    }
  });

  cycle(): void {
    const next: Record<Theme, Theme> = { auto: 'light', light: 'dark', dark: 'auto' };
    this.themeService.setTheme(next[this.themeService.theme()]);
  }
}

<button class="theme-toggle-btn" (click)="cycle()" [attr.aria-label]="label()">
  <lucide-icon [name]="icon()" [size]="22" [strokeWidth]="2"></lucide-icon>
</button>

// src/Web/ClientApp-React/src/components/ThemeToggle.jsx
import { Sun, Moon, Laptop } from 'lucide-react';
import { useTheme } from './ThemeContext';

const icons = {
  auto:  <Laptop size={22} strokeWidth={2} />,
  light: <Sun    size={22} strokeWidth={2} />,
  dark:  <Moon   size={22} strokeWidth={2} />,
};

const next = { auto: 'light', light: 'dark', dark: 'auto' };

export function ThemeToggle() {
  const { theme, setTheme } = useTheme();

  return (
    <button
      className="theme-toggle-btn"
      onClick={() => setTheme(next[theme])}
      aria-label={theme}
    >
      {icons[theme]}
    </button>
  );
}
