// src/Web/ClientApp/src/app/todo/todo.component.ts
import { Component, OnInit, ViewChild, ElementRef, signal, computed, effect } from '@angular/core';
import { TodoListsClient, TodoItemsClient,
  TodoListDto, TodoItemDto, LookupDto,
  CreateTodoListCommand, UpdateTodoListCommand,
  CreateTodoItemCommand, UpdateTodoItemCommand, UpdateTodoItemDetailCommand
} from '../web-api-client';

@Component({
  standalone: false,
  selector: 'app-todo-component',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.scss']
})
export class TasksComponent implements OnInit {
  @ViewChild('newListDialog') newListDialogRef: ElementRef<HTMLDialogElement>;
  @ViewChild('listOptionsDialog') listOptionsDialogRef: ElementRef<HTMLDialogElement>;
  @ViewChild('deleteListDialog') deleteListDialogRef: ElementRef<HTMLDialogElement>;
  @ViewChild('itemDetailsDialog') itemDetailsDialogRef: ElementRef<HTMLDialogElement>;

  lists = signal<TodoListDto[] | null>(null);
  colours = signal<{ name: string, code: string }[]>([]);
  priorityLevels = signal<LookupDto[]>([]);
  selectedListId = signal<number | null>(null);
  selectedList = computed(() => this.lists()?.find(l => l.id === this.selectedListId()) ?? null);
  selectedItem = signal<TodoItemDto | null>(null);
  editingItem = signal<TodoItemDto | null>(null);
  newListEditor: any = {};
  newListError = signal('');
  listOptionsEditor: any = {};
  itemDetailsEditor: any = {};
  newItemTitle = '';
  addingItem = signal(false);
  filter = signal<'all' | 'active' | 'completed'>('all');
  filteredItems = computed(() => {
    const items = this.selectedList()?.items ?? [];
    if (this.filter() === 'active') return items.filter(i => !i.done);
    if (this.filter() === 'completed') return items.filter(i => i.done);
    return items;
  });
  private originalTitle = '';

  constructor(
    private listsClient: TodoListsClient,
    private itemsClient: TodoItemsClient
  ) {
    effect(() => { this.selectedListId(); this.newItemTitle = ''; this.addingItem.set(false); });
  }

  ngOnInit(): void {
    this.listsClient.getTodoLists().subscribe({
      next: result => {
        this.lists.set(result.lists);
        this.priorityLevels.set(result.priorityLevels);
        this.colours.set(result.colours.map(c => ({ name: c.name, code: c.code })));
        if (result.lists.length) {
          this.selectedListId.set(result.lists[0].id);
        }
      },
      error: error => console.error(error)
    });
  }

  // Lists
  remainingItems(list: TodoListDto): number {
    return list.items.filter(t => !t.done).length;
  }

  showNewListDialog(): void {
    this.newListEditor = { colour: this.colours()[0].code };
    this.newListError.set('');
    this.newListDialogRef.nativeElement.showModal();
    setTimeout(() => document.getElementById('title')?.focus(), 50);
  }

  newListCancelled(): void {
    this.newListDialogRef.nativeElement.close();
    this.newListEditor = {};
    this.newListError.set('');
  }

  addList(): void {
    const list = {
      id: 0,
      title: this.newListEditor.title,
      colour: this.newListEditor.colour,
      items: []
    } as TodoListDto;

    this.listsClient.createTodoList({ title: list.title, colour: list.colour } as CreateTodoListCommand).subscribe({
      next: result => {
        list.id = result;
        this.lists.update(ls => [...ls, list]);
        this.selectedListId.set(list.id);
        this.newListDialogRef.nativeElement.close();
        this.newListEditor = {};
        this.newListError.set('');
      },
      error: error => {
        const errors = JSON.parse(error.response).errors;
        if (errors && errors.Title) {
          this.newListError.set(errors.Title[0]);
        }
        setTimeout(() => document.getElementById('title')?.focus(), 50);
      }
    });
  }

  showListOptionsDialog(): void {
    this.listOptionsEditor = {
      id: this.selectedList()!.id,
      title: this.selectedList()!.title,
      colour: this.selectedList()!.colour || this.colours()[0].code
    };
    this.listOptionsDialogRef.nativeElement.showModal();
  }

  closeListOptionsDialog(): void {
    this.listOptionsDialogRef.nativeElement.close();
    this.listOptionsEditor = {};
  }

  updateListOptions(): void {
    const id = this.selectedList()!.id;
    const newTitle = this.listOptionsEditor.title;
    const newColour = this.listOptionsEditor.colour;
    this.listsClient.updateTodoList(id, this.listOptionsEditor as UpdateTodoListCommand).subscribe({
      next: () => {
        this.lists.update(ls => ls.map(l => l.id === id ? { ...l, title: newTitle, colour: newColour } as TodoListDto : l));
        this.closeListOptionsDialog();
      },
      error: error => console.error(error)
    });
  }

  confirmDeleteList(): void {
    this.closeListOptionsDialog();
    this.deleteListDialogRef.nativeElement.showModal();
  }

  closeDeleteListDialog(): void {
    this.deleteListDialogRef.nativeElement.close();
  }

  deleteListConfirmed(): void {
    const deletedId = this.selectedList()!.id;
    this.listsClient.deleteTodoList(deletedId).subscribe({
      next: () => {
        this.closeDeleteListDialog();
        this.lists.update(ls => ls.filter(l => l.id !== deletedId));
        const remaining = this.lists()!;
        this.selectedListId.set(remaining.length ? remaining[0].id : null);
      },
      error: error => console.error(error)
    });
  }

  // Items
  showItemDetailsDialog(item: TodoItemDto): void {
    this.selectedItem.set(item);
    this.itemDetailsEditor = { ...item };
    this.itemDetailsDialogRef.nativeElement.showModal();
  }

  closeItemDetailsDialog(): void {
    this.itemDetailsDialogRef.nativeElement.close();
    this.selectedItem.set(null);
    this.itemDetailsEditor = {};
  }

  updateItemDetails(): void {
    const currentItem = this.selectedItem()!;
    const isMoving = currentItem.listId !== this.itemDetailsEditor.listId;
    this.itemsClient.updateTodoItemDetail(currentItem.id, this.itemDetailsEditor as UpdateTodoItemDetailCommand).subscribe({
      next: () => {
        this.lists.update(ls => ls.map(l => {
          if (l.id === currentItem.listId && isMoving) {
            return { ...l, items: l.items.filter(i => i.id !== currentItem.id) } as TodoListDto;
          }
          if (l.id === this.itemDetailsEditor.listId && isMoving) {
            const moved = { ...currentItem, listId: this.itemDetailsEditor.listId, priority: this.itemDetailsEditor.priority, note: this.itemDetailsEditor.note } as TodoItemDto;
            return { ...l, items: [...l.items, moved] } as TodoListDto;
          }
          if (l.id === currentItem.listId) {
            return { ...l, items: l.items.map(i => i.id === currentItem.id
              ? { ...i, priority: this.itemDetailsEditor.priority, note: this.itemDetailsEditor.note } as TodoItemDto
              : i
            )} as TodoListDto;
          }
          return l;
        }));
        this.closeItemDetailsDialog();
      },
      error: error => console.error(error)
    });
  }

  startAddingItem(): void {
    this.addingItem.set(true);
    setTimeout(() => document.getElementById('newItemInput')?.focus(), 50);
  }

  cancelNewItem(): void {
    this.addingItem.set(false);
    this.newItemTitle = '';
  }

  commitNewItem(): void {
    this.addingItem.set(false);
    if (!this.newItemTitle.trim()) {
      this.newItemTitle = '';
      return;
    }
    const listId = this.selectedListId()!;
    const title = this.newItemTitle.trim();
    this.itemsClient.createTodoItem({ title, listId } as CreateTodoItemCommand).subscribe({
      next: result => {
        this.lists.update(ls => ls.map(l => l.id === listId
          ? { ...l, items: [...l.items, { id: result, listId, title, done: false, priority: this.priorityLevels()[0].id } as TodoItemDto] } as TodoListDto
          : l
        ));
        this.newItemTitle = '';
      },
      error: error => console.error(error)
    });
  }

  editItem(item: TodoItemDto, inputId: string): void {
    this.originalTitle = item.title;
    this.editingItem.set(item);
    setTimeout(() => document.getElementById(inputId)?.focus(), 100);
  }

  cancelEdit(): void {
    if (this.editingItem()) {
      this.editingItem()!.title = this.originalTitle;
    }
    this.editingItem.set(null);
  }

  updateItem(item: TodoItemDto): void {
    if (!item.title.trim()) {
      this.deleteItem(item);
      return;
    }

    if (item.id === 0) {
      const listId = this.selectedListId()!;
      this.itemsClient
        .createTodoItem({ title: item.title, listId } as CreateTodoItemCommand)
        .subscribe({
          next: result => {
            this.lists.update(ls => ls.map(l => l.id === listId
              ? { ...l, items: l.items.map(i => i === item ? { ...i, id: result } as TodoItemDto : i) } as TodoListDto
              : l
            ));
          },
          error: error => console.error(error)
        });
    } else {
      this.itemsClient.updateTodoItem(item.id, item as UpdateTodoItemCommand).subscribe({
        next: () => console.log('Update succeeded.'),
        error: error => console.error(error)
      });
    }

    this.editingItem.set(null);
  }

  deleteItem(item: TodoItemDto): void {
    if (this.itemDetailsDialogRef?.nativeElement.open) {
      this.itemDetailsDialogRef.nativeElement.close();
    }

    const listId = this.selectedListId()!;
    if (item.id === 0) {
      const currentItem = this.selectedItem()!;
      this.lists.update(ls => ls.map(l => l.id === listId
        ? { ...l, items: l.items.filter(i => i !== currentItem) } as TodoListDto
        : l
      ));
      this.editingItem.set(null);
    } else {
      this.itemsClient.deleteTodoItem(item.id).subscribe({
        next: () => {
          this.lists.update(ls => ls.map(l => l.id === listId
            ? { ...l, items: l.items.filter(i => i.id !== item.id) } as TodoListDto
            : l
          ));
        },
        error: error => console.error(error)
      });
    }
  }

  isOverdue(item: TodoItemDto): boolean {
    if (!item.dueDate || item.done) return false;
    return new Date(item.dueDate.toString()) < new Date(new Date().toDateString());
  }
}

<hgroup>
  <h1>Tasks</h1>
  <p>Manage your todo lists and tasks.</p>
</hgroup>

@if (!lists()) {
  <span aria-busy="true">Loading&hellip;</span>
} @else {
  <div class="todo-layout">

    <!-- Sidebar -->
    <div class="todo-sidebar">
      <div class="todo-panel-header">
        <h2>Lists</h2>
        <button class="icon-btn" (click)="showNewListDialog()"><lucide-icon name="plus" [size]="20" [strokeWidth]="2" /></button>
      </div>
      <ul>
        @for (list of lists(); track $index) {
          <li [attr.aria-current]="selectedList() === list ? 'true' : null"
              (click)="selectedListId.set(list.id)">
            <span class="colour-dot" [style.background]="list.colour" aria-hidden="true"></span>
            <span>{{ list.title }}</span>
            <small>{{ remainingItems(list) }}</small>
          </li>
        }
      </ul>
    </div>

    <!-- Items panel -->
    @if (selectedList()) {
      <div class="todo-main">
        <div class="todo-panel-header">
          <h2 [style.color]="selectedList()!.colour">{{ selectedList()!.title }}</h2>
          <button class="icon-btn" (click)="showListOptionsDialog()"><lucide-icon name="settings" [size]="20" [strokeWidth]="2" /></button>
        </div>
        <div class="todo-filters">
          <button [class.active]="filter() === 'all'" (click)="filter.set('all')">All</button>
          <button [class.active]="filter() === 'active'" (click)="filter.set('active')">Active</button>
          <button [class.active]="filter() === 'completed'" (click)="filter.set('completed')">Completed</button>
        </div>
        @for (item of filteredItems(); track $index; let i = $index) {
          <div class="todo-item">
            <input type="checkbox" [(ngModel)]="item.done" (change)="updateItem(item)" />
            @if (item === editingItem()) {
              <input id="{{ 'itemTitle' + i }}" type="text" class="todo-item-input"
                [(ngModel)]="item.title" (keyup.enter)="updateItem(item)"
                (keyup.escape)="cancelEdit(); $event.target.blur()"
                (blur)="editingItem() && updateItem(item)"
                autofocus maxlength="200" />
            } @else {
              <span class="todo-item-text" [class.todo-done]="item.done"
                (click)="editItem(item, 'itemTitle' + i)">{{ item.title }}</span>
              @if (item.dueDate) {
                <small [class.overdue-badge]="isOverdue(item)">
                  {{ isOverdue(item) ? 'Overdue · ' : '' }}{{ item.dueDate | date:'mediumDate' }}
                </small>
              }
            }
            @if (item.id !== 0) {
              <button class="icon-btn" (click)="showItemDetailsDialog(item)"><lucide-icon name="more-horizontal" [size]="20" [strokeWidth]="2" /></button>
            }
          </div>
        }

        <div class="todo-item todo-new-item">
          <input type="checkbox" disabled />
          @if (addingItem()) {
            <input id="newItemInput" type="text" class="todo-item-input"
              [(ngModel)]="newItemTitle"
              (keyup.enter)="commitNewItem()"
              (keyup.escape)="cancelNewItem(); $event.target.blur()"
              (blur)="addingItem() && commitNewItem()"
              maxlength="200" />
          } @else {
            <span class="todo-item-text todo-new-item-placeholder" (click)="startAddingItem()">New task…</span>
          }
        </div>
      </div>
    }

  </div>
}

<!-- New List dialog -->
<dialog #newListDialog>
  <article>
    <header>
      <h3>New List</h3>
      <button rel="prev" aria-label="Close" (click)="newListCancelled()"></button>
    </header>
    <label for="title">Title</label>
    <input type="text" id="title" placeholder="List title&hellip;" [(ngModel)]="newListEditor.title"
      [attr.aria-invalid]="newListError() ? 'true' : null"
      (keyup.enter)="addList()" maxlength="200" />
    @if (newListError()) {
      <small>{{ newListError() }}</small>
    }
    <label>Colour</label>
    <div class="colour-picker">
      @for (c of colours(); track c.code) {
        <button type="button" class="colour-swatch"
          [style.background]="c.code"
          [class.selected]="newListEditor.colour === c.code"
          [attr.aria-label]="c.name"
          (click)="newListEditor.colour = c.code"></button>
      }
    </div>
    <footer>
      <button class="secondary" (click)="newListCancelled()">Cancel</button>
      <button (click)="addList()">Create</button>
    </footer>
  </article>
</dialog>

<!-- List Options dialog -->
<dialog #listOptionsDialog>
  <article>
    <header>
      <h3>List Options</h3>
      <button rel="prev" aria-label="Close" (click)="closeListOptionsDialog()"></button>
    </header>
    <label for="inputListTitle">Title</label>
    <input type="text" id="inputListTitle" placeholder="List name&hellip;"
      [(ngModel)]="listOptionsEditor.title" (keyup.enter)="updateListOptions()" maxlength="200" />
    <label>Colour</label>
    <div class="colour-picker">
      @for (c of colours(); track c.code) {
        <button type="button" class="colour-swatch"
          [style.background]="c.code"
          [class.selected]="listOptionsEditor.colour === c.code"
          [attr.aria-label]="c.name"
          (click)="listOptionsEditor.colour = c.code"></button>
      }
    </div>
    <footer>
      <button class="danger" style="margin-inline-end: auto" (click)="confirmDeleteList()">Delete</button>
      <button class="secondary" (click)="closeListOptionsDialog()">Cancel</button>
      <button (click)="updateListOptions()">Update</button>
    </footer>
  </article>
</dialog>

<!-- Delete List dialog -->
<dialog #deleteListDialog>
  <article>
    <header>
      <h3>Delete "{{ selectedList()?.title }}"?</h3>
      <button rel="prev" aria-label="Close" (click)="closeDeleteListDialog()"></button>
    </header>
    <p>All items will be permanently deleted.</p>
    <footer>
      <button class="secondary" (click)="closeDeleteListDialog()">Cancel</button>
      <button class="danger" style="--pico-background-color: var(--pico-del-color); --pico-border-color: var(--pico-del-color); --pico-color: #fff;" (click)="deleteListConfirmed()">Delete</button>
    </footer>
  </article>
</dialog>

<!-- Item Details dialog -->
<dialog #itemDetailsDialog>
  <article>
    <header>
      <h3>Item Details</h3>
      <button rel="prev" aria-label="Close" (click)="closeItemDetailsDialog()"></button>
    </header>
    <label for="itemList">List</label>
    <select id="itemList" [(ngModel)]="itemDetailsEditor.listId">
      @for (list of lists(); track $index) {
        <option [ngValue]="list.id">{{ list.title }}</option>
      }
    </select>
    <label for="priority">Priority</label>
    <select id="priority" [(ngModel)]="itemDetailsEditor.priority">
      @for (level of priorityLevels(); track $index) {
        <option [ngValue]="level.id">{{ level.title }}</option>
      }
    </select>
    <label for="note">Note</label>
    <textarea id="note" rows="3" [(ngModel)]="itemDetailsEditor.note"></textarea>
    <label for="dueDate">Due Date</label>
    <input type="date" id="dueDate" [(ngModel)]="itemDetailsEditor.dueDate" />
    <footer>
      <button class="danger" style="margin-inline-end: auto" (click)="deleteItem(selectedItem()!)">Delete</button>
      <button class="secondary" (click)="closeItemDetailsDialog()">Cancel</button>
      <button (click)="updateItemDetails()">Update</button>
    </footer>
  </article>
</dialog>

// src/Web/ClientApp-React/src/components/Todo.jsx
import { useState, useEffect, useRef } from 'react';
import { Plus, Settings, MoreHorizontal } from 'lucide-react';
import { TodoListsClient, TodoItemsClient } from '../web-api-client.ts';

const listsClient = new TodoListsClient();
const itemsClient = new TodoItemsClient();

export function Tasks() {
  const [lists, setLists] = useState(null);
  const [priorityLevels, setPriorityLevels] = useState([]);
  const [colours, setColours] = useState([]);
  const [selectedListId, setSelectedListId] = useState(null);
  const [selectedItem, setSelectedItem] = useState(null);
  const [editingItem, setEditingItem] = useState(null);
  const [editValue, setEditValue] = useState('');
  const [newItemTitle, setNewItemTitle] = useState('');
  const [addingItem, setAddingItem] = useState(false);
  const [listOptionsEditor, setListOptionsEditor] = useState({});
  const [itemDetailsEditor, setItemDetailsEditor] = useState({});
  const [newListTitle, setNewListTitle] = useState('');
  const [newListColour, setNewListColour] = useState('');
  const [newListError, setNewListError] = useState('');

  const originalTitle = useRef('');
  const editCancelledRef = useRef(false);
  const newItemCancelledRef = useRef(false);

  const newListDialogRef = useRef(null);
  const listOptionsDialogRef = useRef(null);
  const deleteListDialogRef = useRef(null);
  const itemDetailsDialogRef = useRef(null);

  useEffect(() => {
    listsClient.getTodoLists().then(result => {
      setLists(result.lists);
      setPriorityLevels(result.priorityLevels);
      const apiColours = result.colours.map(c => ({ name: c.name, code: c.code }));
      setColours(apiColours);
      setNewListColour(apiColours[0]?.code ?? '');
      if (result.lists.length) setSelectedListId(result.lists[0].id);
    }).catch(console.error);
  }, []);

  useEffect(() => {
    setNewItemTitle('');
    setAddingItem(false);
  }, [selectedListId]);

  const selectedList = lists?.find(l => l.id === selectedListId) ?? null;
  const remainingItems = list => list.items.filter(t => !t.done).length;

  // ── Lists ──────────────────────────────────────────────────────────────────

  const showNewListDialog = () => {
    setNewListTitle('');
    setNewListColour(colours[0].code);
    setNewListError('');
    newListDialogRef.current.showModal();
    setTimeout(() => document.getElementById('newListTitle')?.focus(), 50);
  };

  const closeNewListDialog = () => {
    newListDialogRef.current.close();
    setNewListTitle('');
    setNewListColour(colours[0].code);
    setNewListError('');
  };

  const commitNewList = async () => {
    if (!newListTitle.trim()) return;
    try {
      const id = await listsClient.createTodoList({ title: newListTitle.trim(), colour: newListColour });
      const newList = { id, title: newListTitle.trim(), colour: newListColour, items: [] };
      setLists(ls => [...ls, newList]);
      setSelectedListId(id);
      closeNewListDialog();
    } catch (e) {
      try {
        const errors = JSON.parse(e.response).errors;
        if (errors?.Title) { setNewListError(errors.Title[0]); return; }
      } catch { /* ignore */ }
      setNewListError('Failed to create list.');
    }
  };

  const showListOptionsDialog = () => {
    setListOptionsEditor({ id: selectedList.id, title: selectedList.title, colour: selectedList.colour || colours[0].code });
    listOptionsDialogRef.current.showModal();
  };

  const closeListOptionsDialog = () => {
    listOptionsDialogRef.current.close();
    setListOptionsEditor({});
  };

  const updateListOptions = async () => {
    try {
      await listsClient.updateTodoList(selectedList.id, listOptionsEditor);
      setLists(ls => ls.map(l => l.id === selectedList.id ? { ...l, title: listOptionsEditor.title, colour: listOptionsEditor.colour } : l));
      closeListOptionsDialog();
    } catch (e) { console.error(e); }
  };

  const confirmDeleteList = () => {
    closeListOptionsDialog();
    deleteListDialogRef.current.showModal();
  };

  const closeDeleteListDialog = () => deleteListDialogRef.current.close();

  const deleteListConfirmed = async () => {
    try {
      await listsClient.deleteTodoList(selectedList.id);
      const remaining = lists.filter(l => l.id !== selectedList.id);
      setLists(remaining);
      setSelectedListId(remaining.length ? remaining[0].id : null);
      closeDeleteListDialog();
    } catch (e) { console.error(e); }
  };

  // ── Items ──────────────────────────────────────────────────────────────────

  const showItemDetailsDialog = (item) => {
    setSelectedItem(item);
    setItemDetailsEditor({ ...item });
    itemDetailsDialogRef.current.showModal();
  };

  const closeItemDetailsDialog = () => {
    itemDetailsDialogRef.current.close();
    setSelectedItem(null);
    setItemDetailsEditor({});
  };

  const updateItemDetails = async () => {
    const isMoving = selectedItem.listId !== itemDetailsEditor.listId;
    try {
      await itemsClient.updateTodoItemDetail(selectedItem.id, itemDetailsEditor);
      setLists(ls => ls.map(l => {
        if (l.id === selectedItem.listId && isMoving)
          return { ...l, items: l.items.filter(i => i.id !== selectedItem.id) };
        if (l.id === itemDetailsEditor.listId && isMoving)
          return { ...l, items: [...l.items, { ...selectedItem, ...itemDetailsEditor }] };
        if (l.id === selectedItem.listId)
          return { ...l, items: l.items.map(i => i.id === selectedItem.id ? { ...i, priority: itemDetailsEditor.priority, note: itemDetailsEditor.note } : i) };
        return l;
      }));
      closeItemDetailsDialog();
    } catch (e) { console.error(e); }
  };

  const deleteItem = async (item) => {
    if (itemDetailsDialogRef.current?.open) closeItemDetailsDialog();
    try {
      await itemsClient.deleteTodoItem(item.id);
      setLists(ls => ls.map(l => l.id === selectedListId
        ? { ...l, items: l.items.filter(i => i.id !== item.id) } : l));
    } catch (e) { console.error(e); }
  };

  const updateCheckbox = async (item, done) => {
    const updated = { ...item, done };
    setLists(ls => ls.map(l => l.id === selectedListId
      ? { ...l, items: l.items.map(i => i.id === item.id ? updated : i) } : l));
    try { await itemsClient.updateTodoItem(item.id, updated); }
    catch (e) { console.error(e); }
  };

  const editItem = (item, inputId) => {
    originalTitle.current = item.title;
    setEditValue(item.title);
    setEditingItem(item);
    setTimeout(() => document.getElementById(inputId)?.focus(), 100);
  };

  const cancelEdit = (e) => {
    editCancelledRef.current = true;
    setLists(ls => ls.map(l => ({
      ...l, items: l.items.map(i => i === editingItem ? { ...i, title: originalTitle.current } : i)
    })));
    setEditingItem(null);
    e?.target.blur();
  };

  const commitEdit = async () => {
    if (!editValue.trim()) {
      await deleteItem(editingItem);
      setEditingItem(null);
      return;
    }
    const updated = { ...editingItem, title: editValue.trim() };
    setLists(ls => ls.map(l => l.id === selectedListId
      ? { ...l, items: l.items.map(i => i === editingItem ? updated : i) } : l));
    setEditingItem(null);
    try { await itemsClient.updateTodoItem(updated.id, updated); }
    catch (e) { console.error(e); }
  };

  const startAddingItem = () => {
    setAddingItem(true);
    setTimeout(() => document.getElementById('newItemInput')?.focus(), 50);
  };

  const cancelNewItem = (e) => {
    newItemCancelledRef.current = true;
    setAddingItem(false);
    setNewItemTitle('');
    e?.target.blur();
  };

  const commitNewItem = async () => {
    setAddingItem(false);
    if (!newItemTitle.trim()) { setNewItemTitle(''); return; }
    const title = newItemTitle.trim();
    const listId = selectedListId;
    setNewItemTitle('');
    try {
      const id = await itemsClient.createTodoItem({ title, listId });
      setLists(ls => ls.map(l => l.id === listId
        ? { ...l, items: [...l.items, { id, listId, title, done: false, priority: priorityLevels[0]?.id }] } : l));
    } catch (e) { console.error(e); }
  };

  if (!lists) return <span aria-busy="true">Loading&hellip;</span>;

  return (
    <>
      <hgroup>
        <h1>Tasks</h1>
        <p>Manage your todo lists and tasks.</p>
      </hgroup>

      <div className="todo-layout">

        {/* Sidebar */}
        <div className="todo-sidebar">
          <div className="todo-panel-header">
            <h2>Lists</h2>
            <button className="icon-btn" onClick={showNewListDialog}><Plus size={20} strokeWidth={2} /></button>
          </div>
          <ul>
            {lists.map(list => (
              <li key={list.id}
                aria-current={selectedList === list ? 'true' : undefined}
                onClick={() => setSelectedListId(list.id)}>
                <span className="colour-dot" style={{ background: list.colour }} aria-hidden="true"></span>
                <span>{list.title}</span>
                <small>{remainingItems(list)}</small>
              </li>
            ))}
          </ul>
        </div>

        {/* Items panel */}
        {selectedList && (
          <div className="todo-main">
            <div className="todo-panel-header">
              <h2 style={{ color: selectedList.colour }}>{selectedList.title}</h2>
              <button className="icon-btn" onClick={showListOptionsDialog}><Settings size={20} strokeWidth={2} /></button>
            </div>

            {selectedList.items.map((item, i) => (
              <div key={item.id} className="todo-item">
                <input type="checkbox" checked={item.done}
                  onChange={e => updateCheckbox(item, e.target.checked)} />
                {editingItem === item ? (
                  <input id={`itemTitle${i}`} type="text" className="todo-item-input"
                    value={editValue}
                    onChange={e => setEditValue(e.target.value)}
                    onKeyDown={e => {
                      if (e.key === 'Enter') { e.target.blur(); }
                      if (e.key === 'Escape') cancelEdit(e);
                    }}
                    onBlur={() => {
                      if (editCancelledRef.current) { editCancelledRef.current = false; return; }
                      commitEdit();
                    }}
                    autoFocus maxLength={200} />
                ) : (
                  <span className={`todo-item-text${item.done ? ' todo-done' : ''}`}
                    onClick={() => editItem(item, `itemTitle${i}`)}>
                    {item.title}
                  </span>
                )}
                {item.id !== 0 && (
                  <button className="icon-btn" onClick={() => showItemDetailsDialog(item)}><MoreHorizontal size={20} strokeWidth={2} /></button>
                )}
              </div>
            ))}

            <div className="todo-item todo-new-item">
              <input type="checkbox" disabled />
              {addingItem ? (
                <input id="newItemInput" type="text" className="todo-item-input"
                  value={newItemTitle}
                  onChange={e => setNewItemTitle(e.target.value)}
                  onKeyDown={e => {
                    if (e.key === 'Enter') commitNewItem();
                    if (e.key === 'Escape') cancelNewItem(e);
                  }}
                  onBlur={() => {
                    if (newItemCancelledRef.current) { newItemCancelledRef.current = false; return; }
                    commitNewItem();
                  }}
                  maxLength={200} />
              ) : (
                <span className="todo-item-text todo-new-item-placeholder"
                  onClick={startAddingItem}>New task…</span>
              )}
            </div>
          </div>
        )}
      </div>

      {/* New List dialog */}
      <dialog ref={newListDialogRef}>
        <article>
          <header>
            <h3>New List</h3>
            <button rel="prev" aria-label="Close" onClick={closeNewListDialog}></button>
          </header>
          <label htmlFor="newListTitle">Title</label>
          <input type="text" id="newListTitle" placeholder="List title…"
            value={newListTitle} onChange={e => setNewListTitle(e.target.value)}
            aria-invalid={newListError ? 'true' : undefined}
            onKeyDown={e => e.key === 'Enter' && commitNewList()}
            maxLength={200} />
          {newListError && <small>{newListError}</small>}
          <label>Colour</label>
          <div className="colour-picker">
            {colours.map(c => (
              <button key={c.code} type="button" className={`colour-swatch${newListColour === c.code ? ' selected' : ''}`}
                style={{ background: c.code }} aria-label={c.name}
                onClick={() => setNewListColour(c.code)} />
            ))}
          </div>
          <footer>
            <button className="secondary" onClick={closeNewListDialog}>Cancel</button>
            <button onClick={commitNewList}>Create</button>
          </footer>
        </article>
      </dialog>

      {/* List Options dialog */}
      <dialog ref={listOptionsDialogRef}>
        <article>
          <header>
            <h3>List Options</h3>
            <button rel="prev" aria-label="Close" onClick={closeListOptionsDialog}></button>
          </header>
          <label htmlFor="listOptionsTitle">Title</label>
          <input type="text" id="listOptionsTitle" placeholder="List name…"
            value={listOptionsEditor.title || ''}
            onChange={e => setListOptionsEditor(ed => ({ ...ed, title: e.target.value }))}
            onKeyDown={e => e.key === 'Enter' && updateListOptions()}
            maxLength={200} />
          <label>Colour</label>
          <div className="colour-picker">
            {colours.map(c => (
              <button key={c.code} type="button" className={`colour-swatch${listOptionsEditor.colour === c.code ? ' selected' : ''}`}
                style={{ background: c.code }} aria-label={c.name}
                onClick={() => setListOptionsEditor(ed => ({ ...ed, colour: c.code }))} />
            ))}
          </div>
          <footer>
            <button className="danger" style={{ marginInlineEnd: 'auto' }} onClick={confirmDeleteList}>Delete</button>
            <button className="secondary" onClick={closeListOptionsDialog}>Cancel</button>
            <button onClick={updateListOptions}>Update</button>
          </footer>
        </article>
      </dialog>

      {/* Delete List dialog */}
      <dialog ref={deleteListDialogRef}>
        <article>
          <header>
            <h3>Delete "{selectedList?.title}"?</h3>
            <button rel="prev" aria-label="Close" onClick={closeDeleteListDialog}></button>
          </header>
          <p>All items will be permanently deleted.</p>
          <footer>
            <button className="secondary" onClick={closeDeleteListDialog}>Cancel</button>
            <button className="danger"
              style={{ '--pico-background-color': 'var(--pico-del-color)', '--pico-border-color': 'var(--pico-del-color)', '--pico-color': '#fff' }}
              onClick={deleteListConfirmed}>Delete</button>
          </footer>
        </article>
      </dialog>

      {/* Item Details dialog */}
      <dialog ref={itemDetailsDialogRef}>
        <article>
          <header>
            <h3>Item Details</h3>
            <button rel="prev" aria-label="Close" onClick={closeItemDetailsDialog}></button>
          </header>
          <label htmlFor="itemList">List</label>
          <select id="itemList" value={itemDetailsEditor.listId || ''}
            onChange={e => setItemDetailsEditor(ed => ({ ...ed, listId: +e.target.value }))}>
            {lists.map(list => (
              <option key={list.id} value={list.id}>{list.title}</option>
            ))}
          </select>
          <label htmlFor="itemPriority">Priority</label>
          <select id="itemPriority" value={itemDetailsEditor.priority || ''}
            onChange={e => setItemDetailsEditor(ed => ({ ...ed, priority: +e.target.value }))}>
            {priorityLevels.map(level => (
              <option key={level.id} value={level.id}>{level.title}</option>
            ))}
          </select>
          <label htmlFor="itemNote">Note</label>
          <textarea id="itemNote" rows={3} value={itemDetailsEditor.note || ''}
            onChange={e => setItemDetailsEditor(ed => ({ ...ed, note: e.target.value }))}></textarea>
          <footer>
            <button className="danger" style={{ marginInlineEnd: 'auto' }} onClick={() => deleteItem(selectedItem)}>Delete</button>
            <button className="secondary" onClick={closeItemDetailsDialog}>Cancel</button>
            <button onClick={updateItemDetails}>Update</button>
          </footer>
        </article>
      </dialog>
    </>
  );
}
