// src/Web/ClientApp/src/app/weather/weather.component.ts
import { ChangeDetectorRef, Component } from '@angular/core';
import { WeatherForecastsClient, WeatherForecast } from '../web-api-client';

@Component({
  standalone: false,
  selector: 'app-weather',
  templateUrl: './weather.component.html'
})
export class WeatherComponent {
  forecasts: WeatherForecast[] = [];
  loading = true;
  error: string | null = null;

  constructor(private client: WeatherForecastsClient, private cdr: ChangeDetectorRef) {
    client.getWeatherForecasts().subscribe({
      next: result => {
        this.forecasts = result;
        this.loading = false;
        this.cdr.detectChanges();
      },
      error: () => {
        this.error = 'Unable to load weather forecasts. Please try again later.';
        this.loading = false;
        this.cdr.detectChanges();
      }
    });
  }
}

<h1>Weather</h1>
<p>This component demonstrates fetching data from the server.</p>

@if (loading) {
  <span aria-busy="true">Fetching your weather forecast&hellip;</span>
}
@if (error) {
  <p class="error">{{ error }}</p>
}
@if (!loading && !error) {
  <table aria-label="Weather forecast">
    <thead>
      <tr>
        <th>Date</th>
        <th>Temp. (C)</th>
        <th>Temp. (F)</th>
        <th>Summary</th>
      </tr>
    </thead>
    <tbody>
      @for (forecast of forecasts; track forecast.date) {
        <tr>
          <td>{{ forecast.date | date }}</td>
          <td>{{ forecast.temperatureC }}</td>
          <td>{{ forecast.temperatureF }}</td>
          <td>{{ forecast.summary }}</td>
        </tr>
      }
    </tbody>
  </table>
}

// src/Web/ClientApp-React/src/components/Weather.jsx
import { useState, useEffect } from 'react';
import { WeatherForecastsClient } from '../web-api-client.ts';

export function Weather() {
  const [forecasts, setForecasts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function fetchData() {
      try {
        const client = new WeatherForecastsClient();
        const data = await client.getWeatherForecasts();
        setForecasts(data);
      } catch (e) {
        setError('Unable to load weather forecasts. Please try again later.');
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  return (
    <div>
      <h1>Weather</h1>
      <p>This component demonstrates fetching data from the server.</p>
      {loading && <span aria-busy="true">Fetching your weather forecast...</span>}
      {error && <p className="error">{error}</p>}
      {!loading && !error && (
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Temp. (C)</th>
              <th>Temp. (F)</th>
              <th>Summary</th>
            </tr>
          </thead>
          <tbody>
            {forecasts.map(forecast =>
              <tr key={forecast.date}>
                <td>{new Date(forecast.date).toLocaleDateString()}</td>
                <td>{forecast.temperatureC}</td>
                <td>{forecast.temperatureF}</td>
                <td>{forecast.summary}</td>
              </tr>
            )}
          </tbody>
        </table>
      )}
    </div>
  );
}
