// src/WebUI/ClientApp-Nuxt/pages/counter.vue
﻿<script>
  const counter = ref(0);
</script>
<template>
  <div>
    <h1>Counter</h1>

    <p>This is a simple example of a Nuxt component.</p>

    <p aria-live="polite">Current count: <strong>{{ counter }}</strong></p>

    <button className="btn btn-primary" @click="counter++">Increment</button>
  </div>
</template>

// src/WebUI/ClientApp/src/app/counter/counter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-counter-component',
  templateUrl: './counter.component.html'
})
export class CounterComponent {
  public currentCount = 0;

  public incrementCounter() {
    this.currentCount++;
  }
}

<h1>Counter</h1>

<p>This is a simple example of an Angular component.</p>

<p aria-live="polite">Current count: <strong>{{ currentCount }}</strong></p>

<button class="btn btn-primary" (click)="incrementCounter()">Increment</button>
