// src/Web/ClientApp-React/src/components/Todo.jsx
import { useState, useEffect, useRef } from 'react';
import { Plus, Settings, MoreHorizontal } from 'lucide-react';
import { TodoListsClient, TodoItemsClient } from '../web-api-client.ts';

const listsClient = new TodoListsClient();
const itemsClient = new TodoItemsClient();

export function Tasks() {
  const [lists, setLists] = useState(null);
  const [priorityLevels, setPriorityLevels] = useState([]);
  const [selectedListId, setSelectedListId] = useState(null);
  const [selectedItem, setSelectedItem] = useState(null);
  const [editingItem, setEditingItem] = useState(null);
  const [editValue, setEditValue] = useState('');
  const [newItemTitle, setNewItemTitle] = useState('');
  const [addingItem, setAddingItem] = useState(false);
  const [listOptionsEditor, setListOptionsEditor] = useState({});
  const [itemDetailsEditor, setItemDetailsEditor] = useState({});
  const [newListTitle, setNewListTitle] = useState('');
  const [newListError, setNewListError] = useState('');

  const originalTitle = useRef('');
  const editCancelledRef = useRef(false);
  const newItemCancelledRef = useRef(false);

  const newListDialogRef = useRef(null);
  const listOptionsDialogRef = useRef(null);
  const deleteListDialogRef = useRef(null);
  const itemDetailsDialogRef = useRef(null);

  useEffect(() => {
    listsClient.getTodoLists().then(result => {
      setLists(result.lists);
      setPriorityLevels(result.priorityLevels);
      if (result.lists.length) setSelectedListId(result.lists[0].id);
    }).catch(console.error);
  }, []);

  useEffect(() => {
    setNewItemTitle('');
    setAddingItem(false);
  }, [selectedListId]);

  const selectedList = lists?.find(l => l.id === selectedListId) ?? null;
  const remainingItems = list => list.items.filter(t => !t.done).length;

  // ── Lists ──────────────────────────────────────────────────────────────────

  const showNewListDialog = () => {
    setNewListTitle('');
    setNewListError('');
    newListDialogRef.current.showModal();
    setTimeout(() => document.getElementById('newListTitle')?.focus(), 50);
  };

  const closeNewListDialog = () => {
    newListDialogRef.current.close();
    setNewListTitle('');
    setNewListError('');
  };

  const commitNewList = async () => {
    if (!newListTitle.trim()) return;
    try {
      const id = await listsClient.createTodoList({ title: newListTitle.trim(), items: [] });
      const newList = { id, title: newListTitle.trim(), items: [] };
      setLists(ls => [...ls, newList]);
      setSelectedListId(id);
      closeNewListDialog();
    } catch (e) {
      try {
        const errors = JSON.parse(e.response).errors;
        if (errors?.Title) { setNewListError(errors.Title[0]); return; }
      } catch { /* ignore */ }
      setNewListError('Failed to create list.');
    }
  };

  const showListOptionsDialog = () => {
    setListOptionsEditor({ id: selectedList.id, title: selectedList.title });
    listOptionsDialogRef.current.showModal();
  };

  const closeListOptionsDialog = () => {
    listOptionsDialogRef.current.close();
    setListOptionsEditor({});
  };

  const updateListOptions = async () => {
    try {
      await listsClient.updateTodoList(selectedList.id, listOptionsEditor);
      setLists(ls => ls.map(l => l.id === selectedList.id ? { ...l, title: listOptionsEditor.title } : l));
      closeListOptionsDialog();
    } catch (e) { console.error(e); }
  };

  const confirmDeleteList = () => {
    closeListOptionsDialog();
    deleteListDialogRef.current.showModal();
  };

  const closeDeleteListDialog = () => deleteListDialogRef.current.close();

  const deleteListConfirmed = async () => {
    try {
      await listsClient.deleteTodoList(selectedList.id);
      const remaining = lists.filter(l => l.id !== selectedList.id);
      setLists(remaining);
      setSelectedListId(remaining.length ? remaining[0].id : null);
      closeDeleteListDialog();
    } catch (e) { console.error(e); }
  };

  // ── Items ──────────────────────────────────────────────────────────────────

  const showItemDetailsDialog = (item) => {
    setSelectedItem(item);
    setItemDetailsEditor({ ...item });
    itemDetailsDialogRef.current.showModal();
  };

  const closeItemDetailsDialog = () => {
    itemDetailsDialogRef.current.close();
    setSelectedItem(null);
    setItemDetailsEditor({});
  };

  const updateItemDetails = async () => {
    const isMoving = selectedItem.listId !== itemDetailsEditor.listId;
    try {
      await itemsClient.updateTodoItemDetail(selectedItem.id, itemDetailsEditor);
      setLists(ls => ls.map(l => {
        if (l.id === selectedItem.listId && isMoving)
          return { ...l, items: l.items.filter(i => i.id !== selectedItem.id) };
        if (l.id === itemDetailsEditor.listId && isMoving)
          return { ...l, items: [...l.items, { ...selectedItem, ...itemDetailsEditor }] };
        if (l.id === selectedItem.listId)
          return { ...l, items: l.items.map(i => i.id === selectedItem.id ? { ...i, priority: itemDetailsEditor.priority, note: itemDetailsEditor.note } : i) };
        return l;
      }));
      closeItemDetailsDialog();
    } catch (e) { console.error(e); }
  };

  const deleteItem = async (item) => {
    if (itemDetailsDialogRef.current?.open) closeItemDetailsDialog();
    try {
      await itemsClient.deleteTodoItem(item.id);
      setLists(ls => ls.map(l => l.id === selectedListId
        ? { ...l, items: l.items.filter(i => i.id !== item.id) } : l));
    } catch (e) { console.error(e); }
  };

  const updateCheckbox = async (item, done) => {
    const updated = { ...item, done };
    setLists(ls => ls.map(l => l.id === selectedListId
      ? { ...l, items: l.items.map(i => i.id === item.id ? updated : i) } : l));
    try { await itemsClient.updateTodoItem(item.id, updated); }
    catch (e) { console.error(e); }
  };

  const editItem = (item, inputId) => {
    originalTitle.current = item.title;
    setEditValue(item.title);
    setEditingItem(item);
    setTimeout(() => document.getElementById(inputId)?.focus(), 100);
  };

  const cancelEdit = (e) => {
    editCancelledRef.current = true;
    setLists(ls => ls.map(l => ({
      ...l, items: l.items.map(i => i === editingItem ? { ...i, title: originalTitle.current } : i)
    })));
    setEditingItem(null);
    e?.target.blur();
  };

  const commitEdit = async () => {
    if (!editValue.trim()) {
      await deleteItem(editingItem);
      setEditingItem(null);
      return;
    }
    const updated = { ...editingItem, title: editValue.trim() };
    setLists(ls => ls.map(l => l.id === selectedListId
      ? { ...l, items: l.items.map(i => i === editingItem ? updated : i) } : l));
    setEditingItem(null);
    try { await itemsClient.updateTodoItem(updated.id, updated); }
    catch (e) { console.error(e); }
  };

  const startAddingItem = () => {
    setAddingItem(true);
    setTimeout(() => document.getElementById('newItemInput')?.focus(), 50);
  };

  const cancelNewItem = (e) => {
    newItemCancelledRef.current = true;
    setAddingItem(false);
    setNewItemTitle('');
    e?.target.blur();
  };

  const commitNewItem = async () => {
    setAddingItem(false);
    if (!newItemTitle.trim()) { setNewItemTitle(''); return; }
    const title = newItemTitle.trim();
    const listId = selectedListId;
    setNewItemTitle('');
    try {
      const id = await itemsClient.createTodoItem({ title, listId });
      setLists(ls => ls.map(l => l.id === listId
        ? { ...l, items: [...l.items, { id, listId, title, done: false, priority: priorityLevels[0]?.id }] } : l));
    } catch (e) { console.error(e); }
  };

  if (!lists) return <span aria-busy="true">Loading&hellip;</span>;

  return (
    <>
      <hgroup>
        <h1>Tasks</h1>
        <p>Manage your todo lists and tasks.</p>
      </hgroup>

      <div className="todo-layout">

        {/* Sidebar */}
        <div className="todo-sidebar">
          <div className="todo-panel-header">
            <h2>Lists</h2>
            <button className="icon-btn" onClick={showNewListDialog}><Plus size={20} strokeWidth={2} /></button>
          </div>
          <ul>
            {lists.map(list => (
              <li key={list.id}
                aria-current={selectedList === list ? 'true' : undefined}
                onClick={() => setSelectedListId(list.id)}>
                <span>{list.title}</span>
                <small>{remainingItems(list)}</small>
              </li>
            ))}
          </ul>
        </div>

        {/* Items panel */}
        {selectedList && (
          <div className="todo-main">
            <div className="todo-panel-header">
              <h2>{selectedList.title}</h2>
              <button className="icon-btn" onClick={showListOptionsDialog}><Settings size={20} strokeWidth={2} /></button>
            </div>

            {selectedList.items.map((item, i) => (
              <div key={item.id} className="todo-item">
                <input type="checkbox" checked={item.done}
                  onChange={e => updateCheckbox(item, e.target.checked)} />
                {editingItem === item ? (
                  <input id={`itemTitle${i}`} type="text" className="todo-item-input"
                    value={editValue}
                    onChange={e => setEditValue(e.target.value)}
                    onKeyDown={e => {
                      if (e.key === 'Enter') { e.target.blur(); }
                      if (e.key === 'Escape') cancelEdit(e);
                    }}
                    onBlur={() => {
                      if (editCancelledRef.current) { editCancelledRef.current = false; return; }
                      commitEdit();
                    }}
                    autoFocus maxLength={200} />
                ) : (
                  <span className={`todo-item-text${item.done ? ' todo-done' : ''}`}
                    onClick={() => editItem(item, `itemTitle${i}`)}>
                    {item.title}
                  </span>
                )}
                {item.id !== 0 && (
                  <button className="icon-btn" onClick={() => showItemDetailsDialog(item)}><MoreHorizontal size={20} strokeWidth={2} /></button>
                )}
              </div>
            ))}

            <div className="todo-item todo-new-item">
              <input type="checkbox" disabled />
              {addingItem ? (
                <input id="newItemInput" type="text" className="todo-item-input"
                  value={newItemTitle}
                  onChange={e => setNewItemTitle(e.target.value)}
                  onKeyDown={e => {
                    if (e.key === 'Enter') commitNewItem();
                    if (e.key === 'Escape') cancelNewItem(e);
                  }}
                  onBlur={() => {
                    if (newItemCancelledRef.current) { newItemCancelledRef.current = false; return; }
                    commitNewItem();
                  }}
                  maxLength={200} />
              ) : (
                <span className="todo-item-text todo-new-item-placeholder"
                  onClick={startAddingItem}>New task…</span>
              )}
            </div>
          </div>
        )}
      </div>

      {/* New List dialog */}
      <dialog ref={newListDialogRef}>
        <article>
          <header>
            <h3>New List</h3>
            <button rel="prev" aria-label="Close" onClick={closeNewListDialog}></button>
          </header>
          <label htmlFor="newListTitle">Title</label>
          <input type="text" id="newListTitle" placeholder="List title…"
            value={newListTitle} onChange={e => setNewListTitle(e.target.value)}
            aria-invalid={newListError ? 'true' : undefined}
            onKeyDown={e => e.key === 'Enter' && commitNewList()}
            maxLength={200} />
          {newListError && <small>{newListError}</small>}
          <footer>
            <button className="secondary" onClick={closeNewListDialog}>Cancel</button>
            <button onClick={commitNewList}>Create</button>
          </footer>
        </article>
      </dialog>

      {/* List Options dialog */}
      <dialog ref={listOptionsDialogRef}>
        <article>
          <header>
            <h3>List Options</h3>
            <button rel="prev" aria-label="Close" onClick={closeListOptionsDialog}></button>
          </header>
          <label htmlFor="listOptionsTitle">Title</label>
          <input type="text" id="listOptionsTitle" placeholder="List name…"
            value={listOptionsEditor.title || ''}
            onChange={e => setListOptionsEditor(ed => ({ ...ed, title: e.target.value }))}
            onKeyDown={e => e.key === 'Enter' && updateListOptions()}
            maxLength={200} />
          <footer>
            <button className="danger" style={{ marginInlineEnd: 'auto' }} onClick={confirmDeleteList}>Delete</button>
            <button className="secondary" onClick={closeListOptionsDialog}>Cancel</button>
            <button onClick={updateListOptions}>Update</button>
          </footer>
        </article>
      </dialog>

      {/* Delete List dialog */}
      <dialog ref={deleteListDialogRef}>
        <article>
          <header>
            <h3>Delete "{selectedList?.title}"?</h3>
            <button rel="prev" aria-label="Close" onClick={closeDeleteListDialog}></button>
          </header>
          <p>All items will be permanently deleted.</p>
          <footer>
            <button className="secondary" onClick={closeDeleteListDialog}>Cancel</button>
            <button className="danger"
              style={{ '--pico-background-color': 'var(--pico-del-color)', '--pico-border-color': 'var(--pico-del-color)', '--pico-color': '#fff' }}
              onClick={deleteListConfirmed}>Delete</button>
          </footer>
        </article>
      </dialog>

      {/* Item Details dialog */}
      <dialog ref={itemDetailsDialogRef}>
        <article>
          <header>
            <h3>Item Details</h3>
            <button rel="prev" aria-label="Close" onClick={closeItemDetailsDialog}></button>
          </header>
          <label htmlFor="itemList">List</label>
          <select id="itemList" value={itemDetailsEditor.listId || ''}
            onChange={e => setItemDetailsEditor(ed => ({ ...ed, listId: +e.target.value }))}>
            {lists.map(list => (
              <option key={list.id} value={list.id}>{list.title}</option>
            ))}
          </select>
          <label htmlFor="itemPriority">Priority</label>
          <select id="itemPriority" value={itemDetailsEditor.priority || ''}
            onChange={e => setItemDetailsEditor(ed => ({ ...ed, priority: +e.target.value }))}>
            {priorityLevels.map(level => (
              <option key={level.id} value={level.id}>{level.title}</option>
            ))}
          </select>
          <label htmlFor="itemNote">Note</label>
          <textarea id="itemNote" rows={3} value={itemDetailsEditor.note || ''}
            onChange={e => setItemDetailsEditor(ed => ({ ...ed, note: e.target.value }))}></textarea>
          <footer>
            <button className="danger" style={{ marginInlineEnd: 'auto' }} onClick={() => deleteItem(selectedItem)}>Delete</button>
            <button className="secondary" onClick={closeItemDetailsDialog}>Cancel</button>
            <button onClick={updateItemDetails}>Update</button>
          </footer>
        </article>
      </dialog>
    </>
  );
}

// src/WebUI/ClientApp/src/app/todo/todo.component.ts
import { Component, TemplateRef, OnInit } from '@angular/core';
import { BsModalService, BsModalRef } from 'ngx-bootstrap/modal';
import { TodoListsClient, TodoItemsClient,
  TodoListDto, TodoItemDto, PriorityLevelDto,
  CreateTodoListCommand, UpdateTodoListCommand,
  CreateTodoItemCommand, UpdateTodoItemCommand
} from '../web-api-client';

@Component({
  selector: 'app-todo-component',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.scss']
})
export class TodoComponent implements OnInit {
  debug = false;
  lists: TodoListDto[];
  priorityLevels: PriorityLevelDto[];
  selectedList: TodoListDto;
  selectedItem: TodoItemDto;
  newListEditor: any = {};
  listOptionsEditor: any = {};
  itemDetailsEditor: any = {};
  newListModalRef: BsModalRef;
  listOptionsModalRef: BsModalRef;
  deleteListModalRef: BsModalRef;
  itemDetailsModalRef: BsModalRef;

  constructor(
    private listsClient: TodoListsClient,
    private itemsClient: TodoItemsClient,
    private modalService: BsModalService
  ) {}

  ngOnInit(): void {
    this.listsClient.get().subscribe(
      result => {
        this.lists = result.lists;
        this.priorityLevels = result.priorityLevels;
        if (this.lists.length) {
          this.selectedList = this.lists[0];
        }
      },
      error => console.error(error)
    );
  }

  // Lists
  remainingItems(list: TodoListDto): number {
    return list.items.filter(t => !t.done).length;
  }

  showNewListModal(template: TemplateRef<any>): void {
    this.newListModalRef = this.modalService.show(template);
    setTimeout(() => document.getElementById('title').focus(), 250);
  }

  newListCancelled(): void {
    this.newListModalRef.hide();
    this.newListEditor = {};
  }

  addList(): void {
    const list = {
      id: 0,
      title: this.newListEditor.title,
      items: []
    } as TodoListDto;

    this.listsClient.create(list as CreateTodoListCommand).subscribe(
      result => {
        list.id = result;
        this.lists.push(list);
        this.selectedList = list;
        this.newListModalRef.hide();
        this.newListEditor = {};
      },
      error => {
        const errors = JSON.parse(error.response);

        if (errors && errors.Title) {
          this.newListEditor.error = errors.Title[0];
        }

        setTimeout(() => document.getElementById('title').focus(), 250);
      }
    );
  }

  showListOptionsModal(template: TemplateRef<any>) {
    this.listOptionsEditor = {
      id: this.selectedList.id,
      title: this.selectedList.title
    };

    this.listOptionsModalRef = this.modalService.show(template);
  }

  updateListOptions() {
    const list = this.listOptionsEditor as UpdateTodoListCommand;
    this.listsClient.update(this.selectedList.id, list).subscribe(
      () => {
        (this.selectedList.title = this.listOptionsEditor.title),
          this.listOptionsModalRef.hide();
        this.listOptionsEditor = {};
      },
      error => console.error(error)
    );
  }

  confirmDeleteList(template: TemplateRef<any>) {
    this.listOptionsModalRef.hide();
    this.deleteListModalRef = this.modalService.show(template);
  }

  deleteListConfirmed(): void {
    this.listsClient.delete(this.selectedList.id).subscribe(
      () => {
        this.deleteListModalRef.hide();
        this.lists = this.lists.filter(t => t.id !== this.selectedList.id);
        this.selectedList = this.lists.length ? this.lists[0] : null;
      },
      error => console.error(error)
    );
  }

  // Items
  showItemDetailsModal(template: TemplateRef<any>, item: TodoItemDto): void {
    this.selectedItem = item;
    this.itemDetailsEditor = {
      ...this.selectedItem
    };

    this.itemDetailsModalRef = this.modalService.show(template);
  }

  updateItemDetails(): void {
    const item = this.itemDetailsEditor as UpdateTodoItemCommand;
    this.itemsClient.updateItemDetails(this.selectedItem.id, item).subscribe(
      () => {
        if (this.selectedItem.listId !== this.itemDetailsEditor.listId) {
          this.selectedList.items = this.selectedList.items.filter(
            i => i.id !== this.selectedItem.id
          );
          const listIndex = this.lists.findIndex(
            l => l.id === this.itemDetailsEditor.listId
          );
          this.selectedItem.listId = this.itemDetailsEditor.listId;
          this.lists[listIndex].items.push(this.selectedItem);
        }

        this.selectedItem.priority = this.itemDetailsEditor.priority;
        this.selectedItem.note = this.itemDetailsEditor.note;
        this.itemDetailsModalRef.hide();
        this.itemDetailsEditor = {};
      },
      error => console.error(error)
    );
  }

  addItem() {
    const item = {
      id: 0,
      listId: this.selectedList.id,
      priority: this.priorityLevels[0].value,
      title: '',
      done: false
    } as TodoItemDto;

    this.selectedList.items.push(item);
    const index = this.selectedList.items.length - 1;
    this.editItem(item, 'itemTitle' + index);
  }

  editItem(item: TodoItemDto, inputId: string): void {
    this.selectedItem = item;
    setTimeout(() => document.getElementById(inputId).focus(), 100);
  }

  updateItem(item: TodoItemDto, pressedEnter: boolean = false): void {
    const isNewItem = item.id === 0;

    if (!item.title.trim()) {
      this.deleteItem(item);
      return;
    }

    if (item.id === 0) {
      this.itemsClient
        .create({ ...item, listId: this.selectedList.id
          } as CreateTodoItemCommand)
        .subscribe(
          result => {
            item.id = result;
          },
          error => console.error(error)
        );
    } else {
      this.itemsClient.update(item.id, item).subscribe(
        () => console.log('Update succeeded.'),
        error => console.error(error)
      );
    }

    this.selectedItem = null;

    if (isNewItem && pressedEnter) {
      setTimeout(() => this.addItem(), 250);
    }
  }

  deleteItem(item: TodoItemDto) {
    if (this.itemDetailsModalRef) {
      this.itemDetailsModalRef.hide();
    }

    if (item.id === 0) {
      const itemIndex = this.selectedList.items.indexOf(this.selectedItem);
      this.selectedList.items.splice(itemIndex, 1);
    } else {
      this.itemsClient.delete(item.id).subscribe(
        () =>
          (this.selectedList.items = this.selectedList.items.filter(
            t => t.id !== item.id
          )),
        error => console.error(error)
      );
    }
  }
}
<h1>Todo</h1>

<p>This is a complex todo list component.</p>

<p *ngIf="!lists"><em>Loading...</em></p>

<div *ngIf="lists">

  <div class="row">
    <div class="col-sm-4">
      <div class="clearfix">
        <h2 class="float-start">Lists</h2>
        <button class="btn btn-default float-end" title="New List..."
          (click)="showNewListModal(newListModalTemplate)">
          <i class="bi bi-journal-plus"></i>
        </button>
      </div>
      <ul class="list-group">
        <li *ngFor="let list of lists; index as i" class="list-group-item"
          [ngClass]="{ 'active': selectedList == list }" (click)="selectedList = list">
          <div class="clearfix">
            <div class="float-start">
              {{ list.title }}
            </div>
            <div class="float-end text-right">
              <span class="badge badge-light">{{ remainingItems(list) }}</span>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class="col-sm-8" *ngIf="selectedList">
      <div class="clearfix">
        <h2 class="float-start">{{ selectedList.title }}</h2>
        <button id="listOptions" class="btn btn-default float-end" title="List Options..."
          (click)="showListOptionsModal(listOptionsModalTemplate)">
          <i class="bi bi-three-dots-vertical"></i>
        </button>
      </div>
      <ul id="todo-items" class="list-group mb-2">
        <li class="list-group-item" *ngFor="let item of selectedList.items; index as i">
          <div class="d-flex">
            <div class="todo-item-checkbox">
              <input type="checkbox" [(ngModel)]="item.done" (change)="updateItem(item)" />
            </div>
            <div class="flex-fill">
              <input id="{{ 'itemTitle' + i }}" *ngIf="item == selectedItem" type="text"
                class="form-control item-input-control" [(ngModel)]="item.title" (keyup.enter)="updateItem(item, true)"
                (blur)="updateItem(item)" autofocus="autofocus" maxlength="200" />
              <div class="todo-item-title" *ngIf="item != selectedItem" [ngClass]="{ 'done-todo': item.done }"
                (click)="editItem(item, 'itemTitle' + i)" class="form-control item-input-control">
                <span>{{ item.title }}</span>
              </div>
            </div>
            <div class="todo-item-commands">
              <button *ngIf="item.id != 0" (click)="showItemDetailsModal(itemDetailsModalTemplate, item)"
                class="btn btn-default btn-xs" role="button">
                <i class="bi bi-three-dots-vertical"></i>
              </button>
            </div>
          </div>
        </li>
        <li class="list-group-item" (click)="addItem()">
          <button class="btn btn-default">Add Item...</button>
        </li>
      </ul>
    </div>
  </div>
</div>

<div *ngIf="debug">
  <pre>{{ lists | json }}</pre>
</div>

<ng-template #listOptionsModalTemplate>
  <div class="modal-header">
    <h4 class="modal-title pull-left">List Options</h4>
    <button type="button" class="close btn-close pull-right" aria-label="Close" (click)="listOptionsModalRef.hide()">
      <span aria-hidden="true" class="visually-hidden">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="form-group">
      <label for="inputListTitle">Title</label>
      <input type="text" class="form-control" id="inputListTitle" placeholder="List name..."
        [(ngModel)]="listOptionsEditor.title" (keyup.enter)="updateListOptions()" maxlength="200" />
    </div>
    <div *ngIf="debug">
      <pre>{{ listOptionsEditor | json }}</pre>
    </div>
  </div>
  <div class="modal-footer">
    <div class="clearfix">
      <div class="float-start">
        <button class="btn btn-default text-danger" (click)="confirmDeleteList(deleteListModalTemplate)">Delete</button>
      </div>
      <div class="float-end">
        <button class="btn btn-default" (click)="listOptionsModalRef.hide()">Cancel</button>
        <button class="btn btn-primary" (click)="updateListOptions()">Update</button>
      </div>
    </div>
  </div>
</ng-template>

<ng-template #itemDetailsModalTemplate>
  <div class="modal-header">
    <h4 class="modal-title pull-left">Item Details</h4>
    <button type="button" class="close btn-close pull-right" aria-label="Close" (click)="itemDetailsModalRef.hide()">
      <span aria-hidden="true" class="visually-hidden">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="form">
      <div class="form-group">
        <label for="list">List</label>
        <select class="form-control" [(ngModel)]="itemDetailsEditor.listId">
          <option [ngValue]="list.id" *ngFor="let list of lists">{{ list.title }}</option>
        </select>
      </div>
      <div class="form-group">
        <label for="priority">Priority</label>
        <select class="form-control" [(ngModel)]="itemDetailsEditor.priority">
          <option [ngValue]="level.value" *ngFor="let level of priorityLevels">{{ level.name }}</option>
        </select>
      </div>
      <div class="form-group">
        <label for="note">Note</label>
        <textarea id="note" class="form-control" rows="3" [(ngModel)]="itemDetailsEditor.note"></textarea>
      </div>
    </div>
    <div *ngIf="debug">
      <pre>{{ itemDetailsEditor | json }}</pre>
    </div>
  </div>
  <div class="modal-footer">
    <div class="clearfix">
      <div class="float-start">
        <button class="btn btn-default text-danger" (click)="deleteItem(selectedItem)">Delete</button>
      </div>
      <div class="float-end">
        <button class="btn btn-default" (click)="itemDetailsModalRef.hide()">Cancel</button>
        <button class="btn btn-primary" (click)="updateItemDetails()">Update</button>
      </div>
    </div>
  </div>
</ng-template>

<ng-template #deleteListModalTemplate>
  <div class="modal-header">
    <h4 class="modal-title pull-left">Delete "{{ selectedList?.title }}"?</h4>
    <button type="button" class="close btn-close pull-right" aria-label="Close" (click)="deleteListModalRef.hide()">
      <span aria-hidden="true" class="visually-hidden">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p>All items will be permanently deleted. </p>
    <div *ngIf="debug">
      <pre>{{ selectedList | json }}</pre>
    </div>
  </div>
  <div class="modal-footer clearfix">
    <div class="float-end">
      <button type="button" class="btn btn-default" (click)="deleteListModalRef.hide()">Cancel</button>
      <button type="button" class="btn btn-danger" (click)="deleteListConfirmed()">Delete</button>
    </div>
  </div>
</ng-template>

<ng-template #newListModalTemplate>
  <div class="modal-header">
    <h4 class="modal-title pull-left">New List</h4>
    <button type="button" class="close btn-close pull-right" aria-label="Close" (click)="newListCancelled()">
      <span aria-hidden="true" class="visually-hidden">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" class="form-control" id="title" placeholder="List title..." [(ngModel)]="newListEditor.title"
        [ngClass]="{ 'is-invalid': newListEditor.error }" (keyup.enter)="addList()" maxlength="200" />
      <div *ngIf="newListEditor.error" class="invalid-feedback">
        {{ newListEditor.error }}
      </div>
    </div>
    <div *ngIf="debug">
      <pre>{{ newListEditor | json }}</pre>
    </div>
  </div>
  <div class="modal-footer clearfix">
    <div class="float-end">
      <button class="btn btn-default" (click)="newListCancelled()">Cancel</button>
      <button class="btn btn-primary" (click)="addList()">Create</button>
    </div>
  </div>
</ng-template>
