// src/Web/ClientApp-React/src/components/Counter.jsx
import { useState } from 'react';

export function Counter() {
  const [count, setCount] = useState(0);

  return (
    <div>
      <h1>Counter</h1>
      <p>This is a simple example of a React component.</p>
      <p aria-live="polite">Current count: <strong>{count}</strong></p>
      <button onClick={() => setCount(c => c + 1)}>Increment</button>
    </div>
  );
}

// src/WebUI/ClientApp-Nuxt/pages/counter.vue
﻿<script>
  const counter = ref(0);
</script>
<template>
  <div>
    <h1>Counter</h1>

    <p>This is a simple example of a Nuxt component.</p>

    <p aria-live="polite">Current count: <strong>{{ counter }}</strong></p>

    <button className="btn btn-primary" @click="counter++">Increment</button>
  </div>
</template>
