// src/Web/ClientApp-React/src/components/NavMenu.jsx
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from './api-authorization/AuthContext';
import { ThemeToggle } from './ThemeToggle';

function AuthLinks() {
  const { isAuthenticated, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = async (e) => {
    e.preventDefault();
    await logout();
    navigate('/login');
  };

  if (isAuthenticated) {
    return <li><a href="#" onClick={handleLogout}>Log out</a></li>;
  }
  return (
    <>
      <li><Link to="/login">Log in</Link></li>
      <li><Link to="/register">Register</Link></li>
    </>
  );
}

export function NavMenu() {
  return (
    <header>
      <nav>
        <ul>
          <li><Link to="/">CleanArchitecture</Link></li>
        </ul>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/counter">Counter</Link></li>
          <li><Link to="/weather">Weather</Link></li>
          <li><Link to="/todo">Tasks</Link></li>
        </ul>
        <ul>
          <AuthLinks />
          <li aria-hidden="true" className="nav-separator"></li>
          <li><ThemeToggle /></li>
        </ul>
      </nav>
    </header>
  );
}

// src/Web/ClientApp/src/app/nav-menu/nav-menu.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/api-authorization/auth.service';

@Component({
  standalone: false,
  selector: 'app-nav-menu',
  templateUrl: './nav-menu.component.html',
  styleUrls: ['./nav-menu.component.scss']
})
export class NavMenuComponent {
  isAuthenticated$ = this.authService.isAuthenticated$;

  constructor(private authService: AuthService, private router: Router) {}

  logout(event: Event): void {
    event.preventDefault();
    this.authService.logout().subscribe({
      next: () => this.router.navigate(['/login'])
    });
  }
}

<header>
  <nav>
    <ul>
      <li><a class="nav-brand" [routerLink]="['/']">CleanArchitecture</a></li>
    </ul>
    <ul>
      <li><a [routerLink]="['/']" [routerLinkActive]="['pico-active']" [routerLinkActiveOptions]="{ exact: true }">Home</a></li>
      <li><a [routerLink]="['/counter']" [routerLinkActive]="['pico-active']">Counter</a></li>
      <li><a [routerLink]="['/weather']" [routerLinkActive]="['pico-active']">Weather</a></li>
      <li><a [routerLink]="['/todo']" [routerLinkActive]="['pico-active']">Tasks</a></li>
    </ul>
    <ul>
      @if (isAuthenticated$ | async) {
        <li><a href="#" (click)="logout($event)">Log out</a></li>
      } @else {
        <li><a [routerLink]="['/login']" [routerLinkActive]="['pico-active']">Log in</a></li>
        <li><a [routerLink]="['/register']" [routerLinkActive]="['pico-active']">Register</a></li>
      }
      <li aria-hidden="true" class="nav-separator"></li>
      <li><app-theme-toggle /></li>
    </ul>
  </nav>
</header>
